export interface Will 
{

  firstEpp: boolean,
  secondEpp: boolean,


  firstParticipants?: string[];

  willNumber:string,
  id:number,
  indCifRecFound?: string,
  clientCode?:string,
  initials?:string,
  language?: string,
  titleCode?:number,
  surname?: string,
  postlAddrLine1?: string,
  postlAddrLine2?: string,
  postlSuburb?: string,
  postlTown?: string,
  postlCodeRsa?: number,
  idDocType?: number,
  idNumber?: string,
  birthDate?: Date,
  maritalStatus?: string,
  smsMarkInd?: string,
  gender?: string,
  minorChildren?: number,
  occupationCode?: number,
  incomeGroup?: number,
  bankingSector?: number,
  securityIndicator?: string,
  liabilityIndicator?: string,
  telebankIndicator?: string,
  unclaimedFundsInd?: string,
  branchClientOpened?: number,
  dateClientOpened?: Date,
  changeNumber?: number,
  dateLastChanged?: Date,
  siteLastChanged?: number,
  tellerLastChanged?: number,
  nbrOfAccounts?: number,
  prohibitedInd?: string,
  postalAddrHold?: string,
  absaRewardIndctor?: string,
  idRequiredHold?: string,
  deceasedEstateHld?: string,
  deceasedSpouseHld?: string,
  insolvntEstateHld?: string,
  curatorshipHold?: string,
  savngStatementHold?: string,
  courtAuthrityHold?: string,
  thirdPartyInd?: string,
  mandateCaptureHld?: string,
  powerAttornyHold?: string,
  sbuSegment?: string,
  mariageContrctType?: number,
  homeLanguage?: string,
  marketingConcent?: string,
  clientType?: number,
  miltaryComtmntInd?: string,
  occupationType?: string,
  noOfJointPartcpnt?: string,
  taxNumber?: number,
  sicCode?: number,
  firstNames?: string,
  insolventIndicator?: string,
  companyYearEnd?: number,
  homeTelCode?: number,
  homeTelephone?: string,
  workTelCode?: number,
  workTelephone?: string,
  physicalAddrHold?: string,
  employerAddrHold?: string,
  cellphone?: number,
  faxWorkCode?: number,
  faxWorkNumber?: number,
  faxHomeCode?: number,
  faxHomeNumber?: number,
  occupationStatus?: number,
  employmentSector?: number,
  occupationLevel?: number,
  practiceNumber?: string,
  clientWebsite?: string,
  contactPerson?: string,
  designation?: number,
  emailAddress?: string,
  inliPolicy?: string,
  exliPolicy?: string,
  instPolicy?: string,
  exstPolicy?: string,
  inivPolicy?: string,
  flexiFuneralPolicy?: string,
  prefrdCommtionMthd?: number,
  cellphoneBankInd?: number,
  siccCode5?: number,
  subSegment?: number,
  emailMarkInd?: string,
  teleMarkInd?: string,
  internetBankinInd?: string,
  sourceOfIncome?: number,
  dateIdentified?: number,
  dateVerified?: number,
  employeeIdentified?: string,
  employeeVerified?: string,
  vatRegistrationNo?: string,
  clientNationality?: string,
  countryOfOrigin?: string,
  dateNClntExempted?: number,
  dateAClntExempted?: string,
  statusOfExemption?: string,
  exemptionIndicator?: string,
  corporateDivision?: string,
  postMatricQualifd?: string,
  postMatricQualfton?: number,
  receiveSocialGrant?: string,
  notifyMeIndicator?: string,
  mailInd?: string,
  applyDebtCounsel?: string,
  dteApplyCounsel?: number,
  counselOrderIssue?: string,
  dteOrderIssue?: number,
  groupScheme?: number,
  groupSchemeEmp?: string,
  secondaryCard?: string,
  affectedPerson?: number,
  exconExpiryDate?: number,
  dateIssued?: number,
  ibrAffected?: string,
  clientGroup?: string,
  nbrOfAddressesRtrv?: number,
  addressEntry?: [
    {
      addrType?: number,
      addrSeqNbr?: number,
      addrLine1?: string,
      addrLine2?: string,
      addrSuburbRsa?: string,
      addrTown?: string,
      addrPostlCode?: number,
    },
    {
      addrType?: number,
      addrSeqNbr?: number,
      addrLine1?: string,
      addrLine2?: string,
      addrSuburbRsa?: string,
      addrTown?: string,
      addrPostlCode?: number,
    },
    {
      addrType?: number,
      addrSeqNbr?: number,
      addrLine1?: string,
      addrLine2?: string,
      addrSuburbRsa?: string,
      addrTown?: string,
      addrPostlCode?: number,
    },
    {
      addrType?: number,
      addrSeqNbr?: number,
      addrLine1?: string,
      addrLine2?: string,
      addrSuburbRsa?: string,
      addrTown?: string,
      addrPostlCode?: number,
    },
    {
      addrType?: number,
      addrSeqNbr?: number,
      addrLine1?: string,
      addrLine2?: string,
      addrSuburbRsa?: string,
      addrTown?: string,
      addrPostlCode?: number,
    }
  ],
  clsPercEntry?: [
    {
      classification?: string,
      percentage?: number,
    },
    {
      classification?: string,
      percentage?: number,
    },
    {
      classification?: string,
      percentage?: number,
    }
  ],
  tempPermitNbr?: string,
  permitExpDte?: number,
  subClassCde?: string,
  countryIncorp?: string,
  inBusinessRescue?: string,
  placedBy?: number,
  dateBusRescueIss?: number,
  ncaThreshold?: string,
  cpaThreshold?: string,
  nkinSurname?: string,
  nkinFname?: string,
  nkinRela?: number,
  nkinDcdh?: string,
  nkinTelh?: string,
  nkinDcdw?: string,
  nkinTelw?: string,
  nkinCell?: string,
  nkinEmail?: string,
  nkinTitle?: number,
  nkinInitials?: string,
  nkinJntSurname?: string,
  reasonCodeO?: number,
  duplClntCode?: [
    { duplCode?: string},
    { duplCode?: string},
    { duplCode?: string}
  ],
  forensicHold?: string,
  updAddressInd?: string,
  updTelephoneInd?: string,
  updEmailInd?: string,
  updDateInd?: number,
  pingitWallet?: string,
  pingitReceive?: string,
  clntExstOnFica?:  string,
  regAddrLine1?: string,
  regAddrLine2?: string,
  regSuburb?: string,
  regTown?: string,
  regCodeRsa?: number,
  hoAddrLine1?: string,
  hoAddrLine2?: string,
  hoSuburb?: string,
  hoTown?: string,
  hoCodeRsa?: number,
  countryResAddress?: string,
  countryHoAddress?: string,
  countryRegAddress?: string,
  countryEntOprtData?: [
    { countryEntOprt?:string},
    
  ],
  countryOfBirth?: string,
  mclInd?: string,
  finCrimeHold?: string,
  clntAgrmntIssued?: string,
  sec129DeliveryAddr?: number,
  saTaxRegis?: string,
  rsonSaTaxNotGiven?: number,
  foreignTaxRegis?: string,
  foreignTaxData?: [
    {
      foreignTaxCtry?: string,
      foreignTaxNo?: string,
      rsonFtaxNotGiven?: number,
    },
    {
      foreignTaxCtry?: string,
      foreignTaxNo?: string,
      rsonFtaxNotGiven?: number,
    },
    {
      foreignTaxCtry?: string,
      foreignTaxNo?: string,
      rsonFtaxNotGiven?: number,
    },
    {
      foreignTaxCtry?: string,
      foreignTaxNo?: string,
      rsonFtaxNotGiven?: number,
    }
  ],
  safeCustody?: string,
  safeCustBoxSmall?: number,
  safeCustBoxMedium?: number,
  safeCustBoxLarge?: number,
  safeCustEnvelope?: number,
  nonCreditIndicator?: string,
  nonCreditDateChanged?: number,
  nonCreditSms?: string,
  nonCreditEmail?: string,
  nonCreditAvoice?: string,
  nonCreditTelephone?: string,
  nonCreditPost?: string,
  creditIndicator?: string,
  creditDateChanged?: number,
  creditSms?: string,
  creditEmail?: string,
  creditAvoice?: string,
  creditTelephone?: string,
  creditPost?: string
}